version: "3.7"
services:
  app:
    container_name: tcp-react
    build: .
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 9000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
